name: Despliegue de la aplicación Terraform

on:
  workflow_call:

jobs:
  deploy-terraform-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MY_AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir="./Terraform/" init

      - name: Terraform Plan
        run: terraform -chdir="./Terraform/" plan

      - name: Terraform Apply
        run: terraform -chdir="./Terraform/" apply -auto-approve