name: Despliegue de la aplicación Docker

on:
  workflow_call:

jobs:
  deploy-docker-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          path: ./Docker

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private
          skip-logout: false
          mask-password: true

      - name: Crear repositorio ECR (si no existe)
        run: |
          aws ecr describe-repositories --repository-names ${{ secrets.ECR_REPOSITORY_DOCKER }} || \
          { aws ecr create-repository \
              --repository-name ${{ secrets.ECR_REPOSITORY_DOCKER }} \
              --region us-east-1 || exit 1; }

      - name: Instalar dependencias Node.js
        run: npm install

      - name: Build de la imagen Docker
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: ./Docker
          push: false 
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_DOCKER }}:latest

      - name: Escaneo de la imagen Docker con Snyk 
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_DOCKER }}:latest
          args: -d

      - name: Push de la imagen Docker
        if: ${{ success() }}  
        uses: docker/build-push-action@v3
        with:
          context: ./Docker
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_DOCKER }}:latest