name: Despliegue de aplicaciones

on:
  push:
    branches: [ main ]

jobs:
  deploy-docker-app:
    uses: ./.github/workflows/deploy-docker.yml

  snyk-security-scan:
    uses: ./.github/workflows/snyk-security.yml
    needs: deploy-docker-app

  deploy-terraform-app:
    uses: ./.github/workflows/deploy-terraform.yml
    needs: snyk-security-scan
