name: Despliegue de aplicaciones

on:
  push:
    branches: [main]

jobs:
  snyk-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Scan IAC code
        run: snyk iac test ./Terraform/** --severity-threshold=high

  deploy-terraform-app:
    runs-on: ubuntu-latest
    needs: snyk-security-scan
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MY_AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurar credenciales de Terraform Cloud
        run: |
          mkdir -p ~/.terraform.d
          echo "{\"credentials\":{\"app.terraform.io\":{\"token\":\"${{ secrets.TERRAFORM_CLOUD_TOKEN }}\"}}}" > ~/.terraform.d/credentials.tfrc.json

      - name: Terraform Init
        run: terraform -chdir="./Terraform/" init

      - name: Terraform Plan
        run: terraform -chdir="./Terraform/" plan

      - name: Terraform Apply
        run: terraform -chdir="./Terraform/" apply -auto-approve

      - name: Obtener dirección IP pública del EC2
        id: output
        run: |
          public_ip=$(terraform -chdir='./Terraform/' output -raw ec2_public_ip)
          echo "::set-output name=public_ip::$public_ip"

      - name: Configurar clave SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/id_rsa
          chmod 400 /tmp/id_rsa
          export SSH_PRIVATE_KEY="/tmp/id_rsa"

      - name: Verificar IP pública de EC2
        run: |
         echo "IP pública: ${{ steps.output.outputs.public_ip }}"

      - name: Verificar conexión SSH
        run: |
          echo "Verificando conexión SSH a EC2..."
          ssh -v -o StrictHostKeyChecking=no -i /tmp/id_rsa ec2-user@${{ steps.output.outputs.public_ip }} "echo 'Conexión exitosa'"

      - name: Verificar existencia de la carpeta 'App'
        run: ls -la ./App

      - name: Copiar aplicación al EC2
        run: |
          echo "Copiando archivos al EC2..."
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ec2-user@${{ steps.output.outputs.public_ip }} "mkdir -p /home/ec2-user/app"
          scp -o StrictHostKeyChecking=no -i /tmp/id_rsa -r ./App ec2-user@${{ steps.output.outputs.public_ip }}:/home/ec2-user/app

      - name: Instalar dependencias y arrancar aplicación en EC2
        run: |
          echo "Instalando dependencias y arrancando la aplicación en EC2..."
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ec2-user@${{ steps.output.outputs.public_ip }} << 'EOF'
            cd /home/ec2-user/app
            npm install
            pm2 start npm --name 'landingpage-yossequiropractica' -- start
          EOF
    env:
      PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

  deploy-docker-app:
    runs-on: ubuntu-latest
    needs: deploy-terraform-app
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Listar archivos en el directorio raíz
        run: ls -la

      - name: Listar archivos del directorio Docker
        run: ls -la ./Docker

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MY_AWS_REGION }}

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Crear repositorio ECR si no existe
        run: |
          aws ecr describe-repositories --repository-names ${{ secrets.ECR_REPOSITORY_DOCKER }} || \
          aws ecr create-repository --repository-name ${{ secrets.ECR_REPOSITORY_DOCKER }} --region ${{ secrets.MY_AWS_REGION }}

      - name: Build de la imagen Docker
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: ./Docker
          file: ./Docker/Dockerfile
          push: false
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_DOCKER }}:latest

      - name: Escaneo de la imagen Docker con Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_DOCKER }}:latest
          args: -d

      - name: Push de la imagen Docker
        if: ${{ success() }}
        uses: docker/build-push-action@v3
        with:
          context: ./Docker
          file: ./Docker/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_DOCKER }}:latest
