name: Escaneo de seguridad con Snyk

on: 
  workflow_call:

jobs:
  snyk-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Escaneo de archivos Terraform con Snyk
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: -d

      - name: Escaneo de la imagen con Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ needs.deploy-docker-app.outputs.registry }}/${{ secrets.ECR_REPOSITORY_DOCKER }}:latest
          args: -d